
HCIMessage = \
    {
        '0x0c03': "Reset",
        '0x1003': "Read Local Supported Features",
        '0x1001': "Read Local Version Information",
        '0x1002': "Read Local Supported Commands (optional)",
        '0x2018': "LE Rand",
        '0x0c33': "Host Buffer Size (optional)",
        '0x0c31': "Set Controller To Host Flow Control (optional)",
        '0x2003': "LE Read Local Supported Features",
        '0x2002': "LE Read Buffer Size",
        '0x201c': "LE Read Supported States",
        '0x202f': "LE Read Maximum Data Length",
        '0x2024': "LE Write Suggested Default Data Length",
        '0x202a': "LE Read Resolving List Size",
        '0x2001': "LE Set Event Mask",
        '0x0c01': "Set Event Mask",
        '0xfc01': "HCI_EXT_SetTxPowerCmd",
        '0xfc02': "HCI_EXT_OnePktPerEvtCmd",
        '0xfc03': "HCI_EXT_ClkDivideOnHaltCmd",
        '0x1009': "Read BD_ADDR",
        '0xfc09': "HCI_EXT_ModemHopTestTxCmd",
        '0x2005': "LE Set Random Address",
        '0x2025': "LE Read Local P256 Public Key 37 0x2025 LE Generate DHKey",
        '0x2006': "LE Set Advertising Parameters",
        '0x2008': "LE Set Advertising Data",
        '0x2009': "LE Set Scan Response Data",
        '0x200a': "LE Set Advertise Enable",
        '0x2016': "LE Read Remote Used Features",
        '0x201b': "LE Long Term Key Requested Negative Reply",
        '0x2032': "Read Local Version Information",
        '0x2020': "LE Remote Connection Parameter Request Reply",
        '0x2026': "LE Read Local P256 Public Key 37 0x2025 LE Generate DHKey",
        '0x2013': "LE Connection Update",
        '0x201a': "LE Long Term Key Requested Reply",
        '0x2027': "LE Add Device to Resolving List",
        '0x204e': "Read Local Version Information",
        '0x202d': "LE Set Address Resolution Enable",
}